import Sidebar from "@/components/Sidebar";
import "../globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Addon from "@/components/Addon";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Curriculum-vites",
  description: "Generated by curriculum-vites",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <div className="flex">
            <Sidebar />
            <span className="h-full border border-gray-100 w-[1px]"></span>
            <div className="w-full h-full">{children}</div>
            <span className="h-full border border-gray-100 w-[1px] ml-14"></span>
            <div className="w-[324px] h-full flex-none">
              <Addon />
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
